# config/cameras.yaml

conveyor_lines:
  - id: 1
    name: "Main Conveyor North"
    source: "rtsp://admin:prg%40adm!n@192.168.193.138:554/cam/realmonitor?channel=1&subtype=1" 
    ppm: 3.3  # Pixels Per Millimeter (Calibration)
    active: true
    camera:
      counting_line_y: 900
      crack_zone: [100, 920, 2400, 1400] # [x1, y1, x2, y2]

  - id: 2
    name: "Secondary Line South"
    source: "tests/Eggs_Sorting.mp4"
    ppm: 3.5
    active: true
    camera:
      counting_line_y: 400
      crack_zone: [50, 410, 1200, 650]

  - id: 3
    name: "Secondary Line South"
    source: "tests/Eggs_Sorting.mp4"
    ppm: 3.5
    active: true
    camera:
      counting_line_y: 400
      crack_zone: [50, 410, 1200, 650]

  - id: 4
    name: "Secondary Line South"
    source: "tests/Eggs_Sorting.mp4"
    ppm: 3.5
    active: true
    camera:
      counting_line_y: 400
      crack_zone: [50, 410, 1200, 650]            