models:
  detection: "models/detection/best.xml" # Train yolo11s.pt with your dataset for detection, NOTE: I did so.
  segmentation: "models/segmentation/best.xml" # Train yolo11n-seg.pt with your dataset for segmentation, NOTE: I did so.

performance:
  cpu_threads: 30
  target_fps: 30

